EditBooks/urls.py
from django.urls import path
from . import views

app_name = 'EditBooks'

urlpatterns = [
    path('', views.searchBooks, name='searchBooks'),
    path('cari_buku/<str:param>/', views.cari_buku, name="cari_buku"),
]

aktivitas/urls.py
from django.urls import path
from . import views

app_name = 'Aktivitas'

urlpatterns = [
    path('', views.aktivity, name='activity'),
]

homepage/urls.py
from django.urls import path
from homepage.views import landing_page, index_page

app_name = 'homepage'

urlpatterns = [
    path('', index_page, name='index'),
    path("homepage/", landing_page, name="homepage"),
]

story6/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('aktivitas/', include('aktivitas.urls', namespace='aktivitas')),
    path('EditBooks/', include('EditBooks.urls', namespace='EditBooks')),
    path('users/', include('users.urls')), # new
    path('users/', include('django.contrib.auth.urls')), # new
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

EditBooks/models.py
from django.db import models

# Create your models here.

aktivitas/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Status(models.Model):
    status = models.TextField(max_length=300, blank=False, null=False)
    date_created = models.DateTimeField(default=datetime.now, blank=False)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager

class CustomUserManager(UserManager):
    pass

class CustomUser(AbstractUser):
	objects = CustomUserManager()
	

EditBooks/forms.py
from django import forms

class searchbox(forms.Form):
    search = forms.CharField()

homepage/forms.py
from django import forms
from homepage.models import Status

class Status_Form(forms.ModelForm):
    class Meta:
        model = Status
        fields = [
            'status'
        ]
    
        labels = {
            'status':'Status',
        }

        required = {
            'status':True
        }

        widgets = {
            'status':forms.Textarea(
                attrs = {
                    'id':'status-input'
                }
            )
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

EditBooks/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json
from .forms import searchbox

# Create your views here.
def searchBooks(request):
    context = {
        'form' : searchbox()
    }
    return render(request, 'books.html', context)

def cari_buku(request, param):
    json = requests.get("https://www.googleapis.com/books/v1/volumes?q=" + param).json()
    return JsonResponse(json)

aktivitas/views.py
from django.shortcuts import render

# Create your views here.
def aktivity(request):
    return render(request,'activity.html')

homepage/views.py
from django.shortcuts import render, redirect
from homepage.models import Status
from homepage.forms import Status_Form
# Create your views here.

def index_page(request):
    return redirect('/homepage/')

def landing_page(request):
    form = Status_Form(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/homepage/')

    statuses = Status.objects.all()
    context = {
        'page_title':'landing',
        'status':statuses,
        'form':form,
    }
    return render(request, 'index.html', context)

users/views.py
from django.shortcuts import render
# users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm


# Create your views here.
def home(request):
    return render(request, 'home.html', {})

def register(request):
    return render(request, 'register.html', {})

class SignUp(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

EditBooks/templates/books.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    <title>Story 8</title>
</head>
<body>
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <a class="navbar-brand" href="{% url 'homepage:index' %}">DahlanYasa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <font face="verdana" color="white">
                <form
                id="searchbox"
                name="searchbox"
                action=""
                method="GET"
                class="sticky-top"
                >
                    {% csrf_token %} {{form}}
                    <input class="btn btn-outline-primary" type="submit" value="submit" />
                </form>
                
            </ul>
        </div>  
    </nav>
    <table class="table table-condensed">
            <thead>
              <tr>
                <th scope="col-3" style="text-align:center;">Image</th>
                <th scope="col-3" style="text-align:center;">Title</th>
                <th scope="col-3" style="text-align:center;">Author</th>
                <th scope="col-3" style="text-align:center;">See Description</th>
              </tr>
            </thead>
            <tbody class="body"></tbody>
    </table>

{% block content %}

<script
    src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"
></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"
></script>
<script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"
></script>
<script src="{% static 'js/daftarBuku.js'%}"></script>



{% endblock %}

EditBooks/templates/buku.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <script
      src="https://kit.fontawesome.com/025b3a9369.js"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>buku</title>
  </head>
  <body>
    <div class="header">
      <button onclick="back()"><i class="fas fa-arrow-left fa-2x"></i></button>
    </div>
    <div class="container konten">Nothing to see here</div>
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/detailBuku.js' %}"></script>
  </body>
</html>

aktivitas/templates/activity.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<div style="margin-top: 10px; display: flex;">
    <div style="flex: 1; margin-right: 10px;">
        <label class="switch">
            <input type="checkbox" id="darkmode-switch">
            <span class="slider round"></span>
        </label>
    </div>
    <div style="flex: 8;">
        <span id="day-night-txt" class="text-bg-color">Day Mode</span>
    </div>
    <div style="flex: 16;"></div>
</div>

<div style="height: 30px;"></div>

<div id="accordion">
    <h3 class="accord-header">Activity</h3>
    <div class="text-bg-color">
        <p>
        -Studying at Faculty of Computer Science<br>
        -Playing games <br>
        -Watching movie<br>
        </p>
    </div>
    <h3 class="accord-header">Organization/commitee experience</h3>
    <div class="text-bg-color">
        <p>
        -Staff of indie games ignite Compfest<br>
        </p>
    </div>
    <h3 class="accord-header">Achievement</h3>
    <div class="text-bg-color">
        <p>
        -Got accepted at University of Indonesia, in Facuty of Computer Science <br>
        </p>
    </div>
</div>

{% endblock %}

aktivitas/templates/navbar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    <title>Story 6, 7, etc.</title>
</head>
<body>
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <a class="navbar-brand" href="#">DahlanYasa</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
                </li> 
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aktivitas:activity' %}">Aktivitas</a>
                </li> 
            </ul>
        </div>  
    </nav>

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="{% static 'js/jscript.js' %}"></script>

</body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>McDy PPW</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  	 	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<link href="{% static 'css/main.css' %}" rel="stylesheet">
	</head>
	<body bgcolor="#6c757d">
		<nav class="navbar navbar-expand-md bg-dark navbar-dark">
			<a class="navbar-brand" href="#">DahlanYasa</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
					<span class="navbar-toggler-icon"></span>
				</button>
			<div class="collapse navbar-collapse" id="collapsibleNavbar">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
					</li> 
					<li class="nav-item">
						<a class="nav-link" href="{% url 'aktivitas:activity' %}">Aktivitas</a>
					</li> 
				</ul>
			</div>  
		</nav>
		{% block content %}
			<div class="text-center">
				<h1>Halo, apa kabar?!</h1>
			</div>
			
			<form method="POST" class="text-center">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit" id="submit-button">Submit</button>
			</form>
			
			{% if not status %}
				<div class='d-flex justify-content-center mt-md-3'>
					<p>Mohon maaf, tidak ada Status yang dapat ditampilkan.</p>
				</div>
			{% else %}
				<div class='table-responsive col-md-6 mt-md-3 mx-auto'>
					<table class='table table-striped'>
						<thead class='thead-dark'>
							<tr>
								<th scope='col' class='align-middle'>#</th>
								<th scope='col' class='align-middle'>Status</th>
								<th scope='col' class='align-middle'>Tanggal/Waktu</th>
							<tr>
						</thead>
						<tbody>
							{% for obj in status %}
								<tr>
									<th scope='row' class='align-middle'>{{forloop.counter}}</th>
									<td class='align-middle'>{{obj.status}}</th>
									<td class='align-middle'>{{obj.date_created}}</th>
								</tr>
							{% endfor %}
						</tbody>
					<table>
				</div>
			{% endif %}
		{% endblock content %}
		
	</body>
</html>

users/templates/home.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
        <div class="landing" id="landing">
            <div class="text-center">
                {% if user.is_authenticated %}
                <h1>
                    <p>Hi {{ user.username }}
                </h1>
                <p><a href="{% url 'logout' %}">Log out</a></p>
                {% else %}
                <h1>
                <p><a href="{% url 'login' %}">Log In </a></p>
                </h1>
                <p><p>Don’t have account?</p><a href="{% url 'signup' %}">Sign Up</a></p>
                {% endif %}
            </div>
        </div>
{% endblock %}

users/templates/signup.html
<!-- templates/signup.html -->
<!-- templates/registration/login.html -->
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
        <!-- templates/signup.html -->
        <div class="lead">
            <h1 class="display-4">Sign Up</h1>
            <h2 class="lead">Please enter your data</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Sign up</button>
            </form>
        </div>
    </section>
{% endblock %}